config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    resources :impressions
    resources :users
    resources :categories
    resources :cities
    resources :comments
    resources :favorites
    resources :jobs
    resources :notifications
    resources :prices
    resources :requests
    resources :reviews

    root to: "impressions#index"
  end

  get 'requests/index'

  get 'requests/show'

  get 'requests/new'
  get 'jobs/all'
  get 'categories/show'
  get 'categories/index'
  get 'jobs/test'



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

 
  get 'users/show'

  get 'favorite_jobs/index'

  get 'users/favorite'

  get 'conversations/index'
  get 'jobs/search' => 'jobs#search', as: 'search_jobs'

  get 'jobs/contact' => 'jobs#contact'
  get 'jobs/tos'
  get 'jobs/aboutus'





  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  resources :jobs
  resources :contacts, only: [:new, :create]

  resources :requests
 

  resources :favorite_jobs, only: [:create,:destroy] 

 

  
  

  resources :conversations do
  member do
    post :reply

    post :trash

    post :untrash
   end
   end


   resources :requests do
    member do
      patch :complete
    end
  end

  resources :users do
    resources :reviews 

  end 

  resources :jobs do
  resources :comments



    
  end 

  
  
  
  
  resources :jobs do
    resources :reviews

    collection do
      get 'search'
   


    end
  end



  
  root 'jobs#index'


end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

 
  

  
   def new
    
      @user = User.find_by(id: params[:recipient_id])
  
   end
  


  
  def create
    recipients = User.find_by(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
  
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

    def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

    def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end
  
  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end
  
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
     
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
    <%= link_to 'Move to trash', trash_conversation_path(conversation) %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
<div class="form-group">
  
 <%= hidden_field_tag(:recipient_id, "#{@user.id}") %></div>
<div class="form-group">
  <%= f.label :subject %>
  <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :message %>
  <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
</div>

<%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @conversation.receipts_for(current_user).each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <small><b>From: <%= message.sender.username %> <br></small>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/_personal_message.html.erb
<p><%= personal_message.body %></p>
<p>at <strong><%= personal_message.created_at %></strong><br>
  by <strong><%= personal_message.user.name %></strong></p>
<hr>

app/views/conversations/index.html.erb
<h1>Your Messages</h1>


 <% @conversations.each do |conversation| %>
  <h1> test </h1>
<div>

<%= link_to conversation.subject, conversation_path(conversation) %> 
</div>

<% end %>

app/views/conversations/new.html.erb
<br>
<br>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<br>
<br>
<br>  


  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
    <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <% if conversation.is_trashed?(current_user) %>
        	<%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    			<% else %>
        		<%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>