config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    resources :impressions
    resources :users
    resources :categories
    resources :cities
    resources :comments
    resources :favorites
    resources :jobs
    resources :notifications
    resources :prices
    resources :requests
    resources :reviews

    root to: "impressions#index"
  end

  get 'requests/index'

  get 'requests/show'

  get 'requests/new'
  get 'jobs/all'
  get 'categories/show'
  get 'categories/index'
  get 'jobs/test'



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

 
  get 'users/show'

  get 'favorite_jobs/index'

  get 'users/favorite'

  get 'conversations/index'
  get 'jobs/search' => 'jobs#search', as: 'search_jobs'

  get 'jobs/contact' => 'jobs#contact'
  get 'jobs/tos'
  get 'jobs/aboutus'





  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  resources :jobs
  resources :contacts, only: [:new, :create]

  resources :requests
 

  resources :favorite_jobs, only: [:create,:destroy] 

 

  
  

  resources :conversations do
  member do
    post :reply

    post :trash

    post :untrash
   end
   end


   resources :requests do
    member do
      patch :complete
    end
  end

  resources :users do
    resources :reviews 

  end 

  resources :jobs do
  resources :comments



    
  end 

  
  
  
  
  resources :jobs do
    resources :reviews

    collection do
      get 'search'
   


    end
  end



  
  root 'jobs#index'


end

app/models/job.rb
 class Job < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	is_impressionable

	#include ImageUploader[:image]
	include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute
	

   #if   @image.blank?
   #has_attached_file :image, default_url: "missing.jpg"
   #end
     
	
	#has_attached_file :image, styles: { medium: "300x300", thumb: "100x100" }, default_url: "spanner"
	#validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



	friendly_id :company, use: :slugged
	belongs_to :user
	belongs_to :price 
	belongs_to :category
	belongs_to :city
	has_many :reviews
	has_many :favorites, as: :favorited
    has_many :fans, through: :favorites, source: :user
    has_many :comments 
    has_many :images
   


	
  
	   
validates_presence_of :title , :description, :price, :phone, :category_id, :city_id

 def average_review
  if reviews.blank?
    @average_review = 0
  else
    @average_review = reviews.average(:rating).round(2)
  end
end






def self.search(search)
	
	if search
		joins(:category).where(["categories.name like ? OR title LIKE ? OR description LIKE ?","%#{search}%", "%#{search}%" , "%#{search}%"])
	else
		

	end

end



#def self.search(search)
  #joins(:category).where(
   # ["categories.name like ? OR title LIKE ? OR description LIKE ?",
    # search, search, search]
 # )
#end





end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_job, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new,  :edit]
	before_action :has_job, only: [:new]
	
	
	def index
			@jobs = Job.all.order("created_at DESC")
			@requests = Request.all.order("created_at DESC")
			#@jobs = Job.search(params[:search])



		end

	def all
		@jobs = Job.all

	end
    

    def contact
    end
	

	def show
     	@jobs = Job.friendly.find(params[:id])

		if @job.reviews.blank?
			@average_review = 0
		else
			@average_review = @job.reviews.average(:rating).round(2)
		

		end
    
	end

	def search
    	@jobs = Job.search(params[:search])
		@requests = Request.search(params[:search])


    end


	

	def new
		

		@job = current_user.jobs.build
		@categories = Category.all.map{  |c|  [c.name, c.id] }
		@cities = City.all.map{  |c|  [c.name, c.id] }
		@prices = Price.all.map{  |c|  [c.name, c.id] }



	end

	def create
        @job = current_user.jobs.build(jobs_params)
        if @job.save
			redirect_to @job, notice: 'Your listing was successfully updated.'
		else
			render :new
		end
	end


	def edit
		@categories = Category.all.map{  |c|  [c.name, c.id] }
		@cities = City.all.map{  |c|  [c.name, c.id] }
		@prices = Price.all.map{  |c|  [c.name, c.id] }
	end



	def update
		@job.category_id = params[:category_id]
		@job.city_id = params[:city_id]
		@job.price_id = params[:price_id]
		if @job.update(jobs_params)
			redirect_to @job, notice: 'Your listing was successfully updated.'
		else
			render "Edit"
		end
	end



	def destroy
		@job.destroy

		redirect_to root_path, notice: 'Your listing was successfully removed.'
	end




	def favdestroy

	Favorite.where(favorited_id: @job.id, user_id: current_user.id).first.destroy
    redirect_to @job, notice: 'Service succesfully removed from favorites'
	
	end

	def test
  @jobs = Job.all
	end

	
   private 

   def has_job
   
  unless current_user.admin
   redirect_to root_path, alert: "You can only post one service at a time" if current_user.jobs.exists?
   end
end 

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id, :city_id, :price_id, :image, :search, :phone, :job_id, :favorite_id)
	end

	def set_job 
		@job = Job.friendly.find(params[:id]) rescue nil
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb

<br>
<br>
<br>
<br>
<div class="container">



<div class="col-md-6 col-md-offset-3">

<br>
  <div class="panel panel-default">


<div class="panel-body">

    <%= simple_form_for(@job, html: {multipart: true}) do |f| %>
	<%#f.collection_select :category_id,Category.all, :id ,:name, {:prompt=> "Select Category" ,:required=> true} %>
	<%#f.collection_select :city_id, City.all, :id ,:name,:prompt=> "Select City" %>

	<%= f.collection_select(:category_id,Category.all, :id ,:name, {:prompt=> "Select Category"} ,{:required=> true}) %>
	<%= f.collection_select(:city_id, City.all, :id, :name, {:prompt => 'Choose a city'}, {:required => true}) %>

	
	<div class="form-group mb-3">
	<br>
	<%= f.input :title,required: true,label: "Your Business Name (required)" %>
	<%= f.input :description,required: true,label: "Tell Us About Your Service (required)" %>
	</div>



    <h5>Choose Pricing:</h5>

	<div><%#f.collection_select :price_id, Price.all, :id ,:name,:prompt=> "Select Pricing (required)" %><div>
		<%= f.collection_select(:price_id, Price.all, :id, :name, {:prompt => 'Select Pricing'}, {:required => true}) %>

	<br>

	



<%= f.input :url, required: false,label: "Website (optional)" %>
<div class= "field">
  
  <%= f.input :image, as: :hidden, input_html: { value: @job.cached_image_data } %>
  <%= f.input :image, as: :file %>
 </div>

<div class= "actions">
  <%#= f.button :submit %>
</div>


	
	<%= f.input :phone, as: :integer, required: true, label: "Enter your phone Number (required)",placeholder: "eg 0722456456"%>
  
	<%# if @job.image.blank? %>
	<%#if @job.cached_image_data.blank? %>
 

	<%# f.file_field :image, label: "Ayoo" %>
	<br>
	<%#else %>

	<%# image_tag @job.cached_image_data ,size: "70x70"  %>

	<%#= f.file_field :image, label: "Ayoo" %></p>
	<br>
	<%# end %>
<center>
	<%= button_tag(type: "submit", class: "btn btn-primary") do %>
  	<span><i class="glyphicon glyphicon-wrench"></i> List Service</span>
	<% end %> 
	</center>


<% end %>
<div align="right"><%= link_to "Back", root_path %></div>

</div>
</div>
</div>
</div>


app/views/jobs/all.html.erb
<br>
<br>
<br>
<br>

<div class="sidenav">

<div><h4> Categories </h4></div>


<% Category.all.each do |category| %>
              
<b><%= link_to category.name, categories_show_path(category: category.name) %></b>
      
            <% end %>
   
       </div>



<center><h4><i class= "fa fa-wrench" ></i>&nbsp;All Services</h4> </center><br>
  
  
<div class="ui container">

<div class="ui grid">
  
<% @jobs.each do |job| %>
 <div class="four wide column">

<div class="ui card" >


<% if job.image.present? %>
<center><div class="image"><%= link_to (image_tag job.image.url, size: "253x200"), job_path(job)   %></div></center>
<% else %>
<center><div class="image"><%= link_to (image_tag "missing.jpg", size: "253x200"), job_path(job)  %></div></center>
<% end %>





  <div class="content">
      <a class="header"><center><%= link_to job.title ,job_path(job) %></center></a>
      <div class="description">
        <%= job.description %>

   
          <% if job.reviews.empty? %>
        <p><div class="average-review-rating" data-score=<%= job.average_review %>></div> <p>  
        No Reviews Yet

       <% else %>

          
               
              <p><div class="average-review-rating" data-score=<%= job.average_review %>></div> <p>   
              <span class="number-of-reviews">Based on  <%= job.reviews.count%>&nbsp;<%= "Review".pluralize(job.reviews.count) %>  </span>  

          
      <% end %>

     




</div>
</div>
</div>
</div>
  
    <% end %>
  </div>
</div>

   <script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/jobs/city.html.erb
<%  @jobs.each do |job| %>



<%= link_to job.company, job_path(job) %>







<% end %> 

app/views/jobs/contact.html.erb
<h1> Contact us </h1>

app/views/jobs/edit.html.erb


<div class="container">
<h3> Edit your service</h3>
</div>
<%= render 'form' %>


<div class="container">
<br>
<%= link_to "Back", root_path %>
</div>




app/views/jobs/index.html.erb

<br>
<br>
 <div class="jumbotron text-center">
      <div class="container-fluid ">
        <h1 class="jumbotron-heading">Welcome to kazify!</h1>
        <p class="lead text-muted">Find service providers or request a task to be completed</p>
       
       <% if user_signed_in? %>
       <% else %>
       <center>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %></a>
         <% end %>
          </center>
          <br>
       <div class="col-md-6 col-md-offset-3">






<%= form_tag search_jobs_path, method: :get do |f| %>

<div class="input-group">
<%= text_field_tag :search, params[:search], :size=> "50", placeholder: "Search For A Service or Request", class: 'form-control' %>
 <span class="input-group-btn">

<%= submit_tag "Search", class: 'btn btn-primary' %>
</div>
</span>
  <% end %>
   




</div>



       
      </div>
    </div>

    




<br>
<div class="ui container">
 <div class="ui message">
  <div class= "ui grid">
    <% Category.all.take(6).each do |category| %>
  <div class="three wide column">

       
  

        
           <h4><%= link_to category.name, categories_show_path(category: category.name), class: "ui primary button" %></h4>
           
         </div>
          <% end %>
       
       </div>

          <p align="right">
          <%= link_to "View all  ", jobs_all_path , class: "btn btn-link" %>
          </p>
     </div>
 </div>






<br>
<br>



<div class="ui container">

<center><h4> Latest Services </h4></center>
<br>

 <div class="ui grid">
<% @jobs.take(12).each do |job| %>
 <div class="four wide column">

<div class="ui card" >


<% if job.image.present? %>
<center><div class="image"><%= link_to (image_tag job.image.url, size: "253x200"), job_path(job)   %></div></center>
<% else %>
<center><div class="image"><%= link_to (image_tag "missing.jpg", size: "253x200"), job_path(job)  %></div></center>
<% end %>





  <div class="content">
      <a class="header"><center><%= job.title %></center></a>
      <div class="description">
        <%# job.description %>
        <%= h truncate(job.description, :length => 80) %>

        <center>
        <% if job.reviews.empty? %>
        <p><div class="average-review-rating" data-score=<%= job.average_review %>></div><p>  
        No Reviews Yet

       <% else %>

          
               
              <p><div class="average-review-rating" data-score=<%= job.average_review %>></div> <p>   
              <span class="number-of-reviews">Based on  <%= job.reviews.count%>&nbsp;<%= "Review".pluralize(job.reviews.count) %>  </span>  

          
      <% end %>
     </center>



</div>
</div>
</div>
</div>
  
    <% end %>

  
  </div>
   <p align="right">
<%= link_to "View all Services >", jobs_all_path , class: "btn btn-link" %>
</p>

</div>
 
<div class="ui grid"> 
 <div class="four wide column"></div> 

</div>

 




  </div>
  </div>
  </div>
</div>

  </div>

  <br>



<br>


        
 <div class="jumbotron jumbotron-custom">
      <div class="container-fluid ">
        <h1 class="jumbotron-custom-heading">Complete requests and make money</h1>
        
       <br>
       <br>
       <br>
       <br>
       <br>
     
    </div>
    </div><br>

    <div class= "ui container">
 <div class="ui message">
       <% Category.all.take(6).each do |category| %>
         <div class="col-md-2"> 
           <h4><%= link_to category.name, categories_index_path(category: category.name), class: "ui primary button" %></h4>
         </div>
       <% end %>
          <p align="right">
          <%= link_to "View all Categories ", requests_index_path , class: "btn btn-link" %>
          </p>
        </div>
      </div>
 
<br>
<br>
<br>


<div class="ui container">


<div class="ui four column grid">





<div class= "ui container">
  <div align="center"><h4>Latest Requests</h4></div>
   <% @requests.all.take(6).each do | request | %>
   <div class="ui segment">
      <div class="ui divided items">
        <div class="item">
           <% if request.user.provider=='facebook' %>
            <a class="ui tiny image">
              <%= image_tag request.user.image, class: "img-circular" %>
            </a>
            <% else %>
        
        <%= link_to (image_tag request.user.avatar),request_path(request), class: "ui tiny image"  %>
              
              <% end %>

                <div class="content" >
                  <h2><a class="header"><%= link_to request.title, request_path(request) %></a></h2>
                          <div class=" description">
                                  <%# request.body ,:length => 80) %>
                                 <%= h truncate(request.body, :length => 280) %>
                                 <div class="city"><b><%= request.city.try(:name) %> </b></div>
                                  <%= link_to "View Request", request_path(request), class: "ui button primary" ,style: "float: right;"%>

                                                </div>
                                                    </div>
                                                        </div>
                                                            </div>
                                                                </div>
                                                                  <% end %>
                                                                     <p align="right">
                                                                      <%= link_to "View all requests ", requests_index_path , class: "btn btn-link" %>
                                                                  </p>

                                                                </div>

</div>




<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>













 


app/views/jobs/new.html.erb
<div class="container">
<h3>New Service</h3>
</div>

<%= render 'form'  %>
<br>

app/views/jobs/search.html.erb
<br>
<br>
<br>
<br>

<div class="container">

<% if @jobs.empty?  %>

<center><h3> No services found </h3></center>
<br>
<br>

</div>



<% else %>
<center><h1> Search Results </h1></center>
 <br>
<div class= "ui container">

 

<div class="panel-body"><center><h4>Services Found</h4> </center></div>
 
  
  





  
<div class="ui grid">
<% @jobs.each do |job| %>
 <div class="four wide column">

<div class="ui card" >


<% if job.image.present? %>
<center><div class="image"><%= link_to (image_tag job.image.url, size: "253x200"), job_path(job)   %></div></center>
<% else %>
<center><div class="image"><%= link_to (image_tag "missing.jpg", size: "253x200"), job_path(job)  %></div></center>
<% end %>





  <div class="content">
      <a class="header"><center><%= link_to job.title ,job_path(job) %></center></a>
      <div class="description">
        <%= job.description %>

   
          <% if job.reviews.empty? %>
        <p><div class="average-review-rating" data-score=<%= job.average_review %>></div> <p>  
        No Reviews Yet

       <% else %>

          
               
              <p><div class="average-review-rating" data-score=<%= job.average_review %>></div> <p>   
              <span class="number-of-reviews">Based on  <%= job.reviews.count%>&nbsp;<%= "Review".pluralize(job.reviews.count) %>  </span>  

          
      <% end %>

     




</div>
</div>
</div>
</div>
  
    <% end %>
  </div>
<% end %>

<% if @requests.empty? %>
<br>
<center><h3> No Requests found </h3></center>

<% else %>
<div class="ui container">


<div class="ui four column grid">





<div class= "ui container">
  <div align="center"><h3>Requests Found</h3></div>
   <% @requests.each do | request | %>
   <div class="ui segment">
      <div class="ui divided items">
        <div class="item">
           <% if request.user.provider=='facebook' %>
            <a class="ui tiny image">
              <%= image_tag request.user.image, class: "img-circular" %>
            </a>
            <% else %>
        
        <%= link_to (image_tag request.user.avatar),request_path(request), class: "ui tiny image"  %>
              
              <% end %>

                <div class="content" >
                  <a class="header"><%= link_to request.title, request_path(request) %></a>
                          <div class=" description">
                                  <%= request.body %>
                                  <%= request.city.try(:name) %>
                                  <%= request.category.try(:name) %>
                                  <%= link_to "View Request", request_path(request), class: "ui button primary" ,style: "float: right;"%>

                                                </div>
                                                    </div>
                                                        </div>
                                                            </div>
                                                                </div>
                                                                  <% end %>
                                                                 

                                                                </div>
                                                                <% end %>

</div>





 <script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/jobs/show.html.erb
<br>
<br>
<br>
<div class= "container">
<div class="row">
  

	<div class="col-md-4 col-md-offset-1">
	<br>
	<div class= "thumbnails">
    
    <div id="popup">



    	   <% if @job.image.present? %>
    <%# if @job.images.size %>

    <%# @jobs.images.each do|image| %>
	<%= image_tag @job.image.url , width: 150  %>

	<% else %>
		<%= image_tag "missing.jpg" %>

				<% end %>
</div>



	</div>
<script type="text/javascript">
  $(document).ready(function() {
     $(".popup_link").click(function(e) {
        e.preventDefault();
        $("#popup").html( $('<img>').attr('src', this.href) );
     });
  });
</script>

 <div class="col-md-14">
		   <div class="panel panel-default">
          <div class="panel-body">
     
     <center>





<%if @job.user.provider=='facebook' %>
   	<p>Posted by <%= link_to(@job.user.name, @job.user) %></p>
	
	<%= link_to (image_tag @job.user.image, :class=> "img-circular"), @job.user %>

  <% else %>
          <p>Posted by <%= link_to(@job.user.first_name, @job.user) %></p>
          <%= link_to (image_tag @job.user.avatar, :class=> "img-circular"), @job.user %>

          <% end %>





	

	<p>Joined<%= @job.user.created_at.strftime(" %b %d, %Y") %></p>
	<div>Verified Accounts:</div>

<%if user_signed_in? && current_user.provider=='facebook' %>
<%= image_tag "fb.png", size: "50x50" %>
<% else %>

<% end %>
	<p><%= link_to("Seller's Profile", @job.user) %><p>

     </center>
	
    </div>
    </div>
    </div>



   <div class="col-md-14">
		   <div class="panel panel-default">
         
         <div class="panel-body">
         <center>
     <h3>Contact</h3>
     <% if user_signed_in? %>
	<p><span class="glyphicon glyphicon-earphone glyphicon-align-left" aria-hidden="true">&nbsp;</span><%= @job.phone %></p>
	<% else %>

	<p> <%= link_to "Sign in" , user_session_path %> to view contact information </p>

	<% end %>
   
    <% if user_signed_in? %>
   
	<%if @job.user_id == current_user.id %>

	<% else %>
    
	<%= link_to "Message Seller", new_conversation_path(:recipient_id => @job.user.id), class: "btn btn-large btn-primary" %>
	<% end %>
	<% end %>
	</center>
    </div>
    </div>
    </div>



 <div class="col-md-14">
		   <div class="panel panel-default">
          <div class="panel-body">
     <center><h4>Share</h4></center>
     <center>
     <p><%= social_share_button_tag(@job.title) %></p>

     </center>
	
    </div>
    </div>
    </div>




   </div>
	


    







	<div class="col-md-6">
    <br>
    <div class="panel panel-default">
    <div class="panel-body">

    <center>
	<h3><%= @job.title %></h3>
	<p>Posted on <%= @job.created_at.strftime(" %b %d, %Y") %></p>

	<p><%= @job.description %></p>
	<p><%= @job.category.try(:name)%></p>
	<p>Pricing: <%= @job.price.try(:name) %>
    <i class="fa fa-building-o"></i><p><%= @job.city.try(:name) %></p>
    <p><%= @job.url %><p>
	

	<p>
    Views&nbsp;<span class="glyphicon glyphicon-eye-open glyphicon-align-left" aria-hidden="true"></span>&nbsp;<%= @job.impressionist_count %>

	</p>

	<% if user_signed_in? %>


<%# if @job.user_id == current_user.id %>
 <% if current_user == @job.user || current_user.admin? %>





<%= link_to "Edit", edit_job_path(@job) ,class: "btn btn-md btn-primary"  %>
<%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure to permanently delete this listed service?" }, class: "btn btn-md btn-danger" %>

<% else %>

<% if current_user.admin? %>

<%= link_to "Edit", edit_job_path(@job) ,class: "btn btn-md btn-primary"  %>
<%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure to permanently delete this listed service?" }, class: "btn btn-md btn-danger" %>






<% end %>
<% end %>

<% end %>

	<h4>Average Rating</h4>
<div class="average-review-rating" data-score=<%= @average_review %>></div>
<% if user_signed_in? %>
<% if @job.user_id == current_user.id %>
<% if @job.reviews.empty? %>

<p> No one has reviewed your service yet </p>

<% else %>

<% if @job.reviews.empty? %>


<p>No reviews have been added yet <%= link_to 'be the first',  new_job_review_path(@job)  %> </p>
<% else %>
<span class="number-of-reviews">Based on <%= @job.reviews.count%>&nbsp;<%= "Review".pluralize(@job.reviews.count) %> </span>  

<% end %>
<% end %>
<% end %>
<% end %>


<% if user_signed_in? %>
<% if @job.user_id == current_user.id %>

<% else %>

<div><%= link_to "Write A Review", new_job_review_path(@job) %> </div>
<% end %>
<% end %>

	</center>
	</div>
	</div>


<%= render @job.reviews %>



	</div>
</div>









</div>
</div>

</div>
<br>
<div class= "container">

<br>
<p><%# link_to 'Report' , report_path %> </p>
</div>







</div>

<%# if user_signed_in? %>

<%# unless current_user.favorite_jobs.exists?(id: @job.id) -%>
          <%# link_to 'Add to favorites', favorite_jobs_path(@job),class: "btn btn-sm danger", method: :post  %>
          <%# else -%>
          <%# link_to 'Remove from favorites', favorite_job_path(@job), method: :delete ,class: "btn btn-sm warning"%>
          <%# end -%>


          <%# end %>


</div>




<script>

$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});

</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>


app/views/jobs/test.html.erb
<br>
<br>

<h4> Latest Services </h4>

<div class="ui four column grid">
<% @jobs.take(12).each do |job| %>


	<div class="four wide column">
<% if job.image.present? %>
<%= image_tag job.image.url , class: "ui centered small image"  %>
<% else %>

<%= image_tag "missing.jpg", class: "ui centered small image" %>
<% end %>




  <div class="content">
      <a class="header"><%= job.title %></a>
      <div class="description">
        <%= job.description %>
</div>
      </div>
    
  </div>


    <% end %>
    </div>
 