config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    resources :impressions
    resources :users
    resources :categories
    resources :cities
    resources :comments
    resources :favorites
    resources :jobs
    resources :notifications
    resources :prices
    resources :requests
    resources :reviews

    root to: "impressions#index"
  end

  get 'requests/index'

  get 'requests/show'

  get 'requests/new'
  get 'jobs/all'
  get 'categories/show'
  get 'categories/index'
  get 'jobs/test'



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

 
  get 'users/show'

  get 'favorite_jobs/index'

  get 'users/favorite'

  get 'conversations/index'
  get 'jobs/search' => 'jobs#search', as: 'search_jobs'

  get 'jobs/contact' => 'jobs#contact'
  get 'jobs/tos'
  get 'jobs/aboutus'





  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  resources :jobs
  resources :contacts, only: [:new, :create]

  resources :requests
 

  resources :favorite_jobs, only: [:create,:destroy] 

 

  
  

  resources :conversations do
  member do
    post :reply

    post :trash

    post :untrash
   end
   end


   resources :requests do
    member do
      patch :complete
    end
  end

  resources :users do
    resources :reviews 

  end 

  resources :jobs do
  resources :comments



    
  end 

  
  
  
  
  resources :jobs do
    resources :reviews

    collection do
      get 'search'
   


    end
  end



  
  root 'jobs#index'


end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :notifications, foreign_key: :recipient_id
	has_many :jobs
  has_many :requests
	has_many :reviews
	has_many :favorites
  
  has_many :favorite_jobs, through: :favorites, source: :favorited, source_type: 'Job'


    
  
  acts_as_messageable 
  

  if @avatar.blank?
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.jpg"
  has_attached_file :avatar, default_url: "missing.jpg"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  else 
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  end
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
 
         :recoverable, :rememberable, :trackable, :validatable,

         :omniauthable, :omniauth_providers => [:facebook]




    def update_with_password(params, *options)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if params[:password].blank? || valid_password?(current_password)
      update_attributes(params, *options)
    else
      self.assign_attributes(params, *options)
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end

    clean_up_passwords
    result
end 



def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end


def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.avatar = auth.info.image # assuming the user model has an image # this was user.image i changed it to experiment
    user.first_name = auth.info.first_name


  end

end


  

def mailboxer_email(object)

  nil
 end 


         

 
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def favorite

		@jobs = current_user.favorite_jobs
	end 
		


		


 	#def destroy

		#Favorite.where(favorited_id: @job.id, user_id: current_user.id).first.destroy
    	#redirect_to @job, notice: 'Service succesfully removed from favorites'
	#
def destroy
	sign_out
    redirect_to root_url
end 




  	def show
  		@user = User.find(params[:id])
  	end 


  	def edit

  		@user = User.find(params[:id])

  	end 

  	def update 
	 	@user = User.find(params[:id])  
	 
			if @user.update(user_params)
				redirect_to @user, :notice => "Succesfully Updated Profile"
			else
			render "Edit"
			end
 
 	end 




	private 



	def user_params
	params.require(:user).permit(:first_name, :last_name, :user, :job_id, :favorite_id, :user_id)
	end

 
 end 

app/helpers/users_helper.rb
module UsersHelper



end 

app/views/users/favorite.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

   
 
  
 
<% if @current_user.favorite_jobs.each do |job| %>
  <%= link_to job.company, job_path(job) %>

    <%= image_tag (job.job_img.url :job_index) %>
<% end.empty? %>
  You have not added any favorites.
<% end %>


  


 








</div>

app/views/users/index.html.erb
<% @current_user.favorite_jobs.each do |job| %>


<%= link_to job.company, job_path(job) %>

<%= image_tag (job.job_img.url :job_index) %>

<% end %>

app/views/users/show.html.erb
<br>
<br>
<br>
<div class = "container">
<div class="col-md-10 col-md-offset-1">
<br>
<div class="panel panel-default">


<div class="panel-body">
<center>
<%if @user.provider=='facebook' %>
<p><%= image_tag @user.image, class: "img-circular" %></p>
<% else %>
<p><%= image_tag @user.avatar, class: "img-circular" %></p>
<% end %>

<% if @user.name.blank? %>
<%= @user.first_name %> <%= @user.last_name %>
<% else %>
<%= @user.name %>
<%# else %>

<% end %>


<p>Joined<%= @user.created_at.strftime(" %b %d, %Y") %></p>
<p>Verified Accounts:</p>
<%if user_signed_in? && current_user.provider=='facebook' %>
<%= image_tag "fb.png", size: "50x50" %>
<% else %>

<% end %>

</center>
</div>
</div>
</div>
</div>





<br>
<div class="container">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-default">


<div class="panel-body">
<% if @user == current_user %> 
<center><h4>Your Listings</h4></center>
<% else %>
 <%if @user.provider=='facebook' %>
<center><h4>Jobs posted by <%= @user.name %></h4></center>
<% else %>
<center><h4>Jobs posted by <%= @user.first_name %> <%= @user.last_name %></h4></center>
<% end %>
<% end %>
<table class="table table-borderless">



<% if @user != current_user && @user.jobs.empty? %>
	
<center><p> User has not posted any jobs</p></center>

<% else %>


<% if @user == current_user && @user.jobs.empty? %>

<center><p> You have not posted any jobs</p></center>



<% else %>

	
<%  @user.jobs.each do |job| %>
<tr>
	<%# if job.image.present? %>
	
  <td><%= image_tag job.image_url, size: "70x70" %></td>


	 <%# else %>


<%# link_to (image_tag "missing.jpg", size:"70x70" ), job_path(job) %>

<td><%= job.category.try(:name)%></td>
<td><%= job.description %></td>
<td><%= job.city.try(:name) %></td>

<td><%= link_to "View Service" , job_path(job), class: "btn btn-md btn-primary" %></td>


<%# if @user == current_user %>
<td><%# link_to "Delete Service", job_path(job), method: :delete, data: { confirm: "The Listed Service will be permanently deleted from your profile & Listings,Are you Sure?" }, class: "btn btn-md btn-danger" %></td>

</tr>

<%# end %>

<%# end %>
<% end %>
<% end %>
<% end %>


</table>
</div>

</div>
</div>
</div>


<div class="container">
	<div class="col-md-6 col-md-offset-1">
		<div class="panel panel-default">
			<div class="panel-body">
			<div class="panel-heading"><center><H3>Reviews Posted</h3></center></div>


<% if @user != current_user && @user.reviews.empty? %>
	
<center><p> User has not posted any reviews</p></center>

<% else %>


<% if @user == current_user && @user.reviews.empty? %>

<center><p> You have not posted any reviews</p></center>


<% @user.reviews.each do |review| %>






 <%if @user.provider=='facebook' %>

<center><%= image_tag review.user.image, class: "img-circular" %>
	<% else %>
	<center><%= image_tag review.user.avatar, class: "img-circular" %>
		<% end %>


<div><h3><%= review.job.title %></h3></div>
<div class="review-rating" data-score="<%= review.rating %>"></div>

<div><%= review.comment %></div></center>
<br>





<% if user_signed_in? %>

<% if @user == current_user %>



<div><p align="right"><%= link_to "Edit", edit_job_review_path(review.job, review) %>
<%= link_to "Delete", job_review_path(review.job, review),method: :delete, data: { confirm: "Are you sure?"} %><p></div>


<% end %>
<% end %>


<% end %>
<% end %>
<% end %>


</div>
	</div>
		</div>
			</div>

 


  
<script>

$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});

</script>