config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    resources :impressions
    resources :users
    resources :categories
    resources :cities
    resources :comments
    resources :favorites
    resources :jobs
    resources :notifications
    resources :prices
    resources :requests
    resources :reviews

    root to: "impressions#index"
  end

  get 'requests/index'

  get 'requests/show'

  get 'requests/new'
  get 'jobs/all'
  get 'categories/show'
  get 'categories/index'
  get 'jobs/test'



  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox

  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent

  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

 
  get 'users/show'

  get 'favorite_jobs/index'

  get 'users/favorite'

  get 'conversations/index'
  get 'jobs/search' => 'jobs#search', as: 'search_jobs'

  get 'jobs/contact' => 'jobs#contact'
  get 'jobs/tos'
  get 'jobs/aboutus'





  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users
  resources :jobs
  resources :contacts, only: [:new, :create]

  resources :requests
 

  resources :favorite_jobs, only: [:create,:destroy] 

 

  
  

  resources :conversations do
  member do
    post :reply

    post :trash

    post :untrash
   end
   end


   resources :requests do
    member do
      patch :complete
    end
  end

  resources :users do
    resources :reviews 

  end 

  resources :jobs do
  resources :comments



    
  end 

  
  
  
  
  resources :jobs do
    resources :reviews

    collection do
      get 'search'
   


    end
  end



  
  root 'jobs#index'


end

app/models/request.rb
class Request < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	is_impressionable

	has_attached_file :image, styles: { medium: "250x", thumb: "50x" }, default_url: "missing2"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	belongs_to :user
	
	
	belongs_to :category
	belongs_to :city
	validates_presence_of :title, :body, :budget ,:contact 
	has_many :favorites, as: :favorited
    has_many :fans, through: :favorites, source: :user
    has_many :comments 



   validates_presence_of :title , :body, :category_id, :city_id
   validates :budget, presence: true , numericality: true
   validates :contact, presence: true , numericality: true, length:{minimum: 8, maximum: 10}


 def completed?
 	!completed_at.blank?
 end








def self.search(search)
	
	if search
		joins(:category).where(["categories.name like ? OR title LIKE ? OR body LIKE ?","%#{search}%", "%#{search}%" , "%#{search}%"])
	else
		

	end

end


end 

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :set_request, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new,  :edit]
  before_action :has_request, only: [:new]
  def index
  	@requests = Request.all
  end

  def new
  	@request = current_user.requests.build
  	@categories = Category.all.map{  |c|  [c.name, c.id] }
	  @cities = City.all.map{  |c|  [c.name, c.id] }
  end

  def search

  end 

  def complete
    @request.update_attribute(:completed_at, Time.now)
  end 

  def create

  	@request = current_user.requests.build(request_params)


		respond_to do |format|
			if @request.save
				format.html { redirect_to @request, notice: 'Your Request is now live!'}

					else 
			 format.html { render :new}

			end
		end

	end

		
		
  def show
	@requests = Request.friendly.find(params[:id])
  #@relative_requests = @request.category.request
  end 
  

  def edit 
  	@categories = Category.all.map{  |c|  [c.name, c.id] }
    @cities = City.all.map{  |c|  [c.name, c.id] }
  end 
   
  def update
   	@request.category_id = params[:category_id]
	  @request.city_id = params[:city_id]
		
   	 if @request.update(request_params)
   	 	redirect_to @request, notice: 'Your Request was successfully updated.' 
      else
        render "Edit"
      end 
   end



  def destroy
   	@request.destroy
   	redirect_to root_path , notice: 'Your listing was successfully removed.'
  end

  def complete
    @request = Request.friendly.find(params[:id])
    @request.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end 


  private 

  def has_request
  redirect_to root_path, alert: "You can only post one request at a time" if current_user.requests.exists?
  end

	def request_params
		params.require(:request).permit(:title, :body, :budget, :category_id, :city_id, :search, :contact, :request_id)
	end

	def set_request 
		@request = Request.friendly.find(params[:id]) rescue nil 
	end


end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
  
 <div class="container center_div">
  
  <div class="row">


<div class="col-md-6 col-md-offset-3">


<div class="panel panel-default">
  <div class="panel-body">


<%= simple_form_for(@request, html: {multipart: true}) do |f| %>

<h5>Select Category:

	<%= f.collection_select(:category_id,Category.all, :id ,:name, {:prompt=> "Select Category"} ,{:required=> true}) %>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<%= f.collection_select(:city_id, City.all, :id, :name, {:prompt => 'Choose a city'}, {:required => true}) %>

<br>





<%= f.input :title, required: true, label: "Title of your Request " , placeholder: "eg looking for a cleaner"%>



<%= f.input :body, required: true, label: "Describe your request in detail",placeholder: "eg i'm hosting a party for the weekend and i need someone to cleanup afterwords" %>



<%= f.input :budget, as: :integer ,required: true,label: "Set your Budget for this Request"%>




<%= f.input :contact, as: :integer, required: true, label: "Enter your phone Number",placeholder: "eg 0722-456-456"%>





<center>
<div class= "action">
<%= button_tag(type: "submit", class: "btn btn-primary") do %>
  <span><i class="glyphicon glyphicon-wrench"></i> Create Request</span>
  </div>

<% end %> 
<div align="right"><%= link_to "Back", root_path %></div>
</div>
</div>
</div>
</div>
</div>




 
 <% end %>

app/views/requests/edit.html.erb
<div class="container">
<br>
<br>
<br>
<center><h3> Edit Request </h3></center>
</div>

<%= render 'form' %>

app/views/requests/index.html.erb
<br>
<br>
<br>
<br>


<div class="sidenav">

<div><h4> Categories </h4></div>

<% Category.all.each do |category| %>
              
<%= link_to category.name, categories_index_path(category: category.name) %>

      
            <% end %>

       </div>

<div class="container">


<div class="ui four column grid">




<center><h4>Latest Requests</h4> </center>
<div class= "ui container">
   <% @requests.all.each do | request | %>
   <div class="ui segment">
      <div class="ui divided items">
        <div class="item">
           <% if request.user.provider=='facebook' %>
            <a class="ui tiny image">
              <%= image_tag request.user.image, class: "img-circular" %>
            </a>
            <% else %>
        
        <%= link_to (image_tag request.user.avatar),request_path(request), class: "ui tiny image"  %>
              
              <% end %>

                <div class="content" >
                  <a class="header"><%= link_to request.title, request_path(request) %></a>
                          <div class=" description">
                                  <%= request.body %>
                                  <%= request.city.try(:name) %>
                                  <%= link_to "View Request", request_path(request), class: "ui button primary" ,style: "float: right;"%>

                                                </div>
                                                    </div>
                                                        </div>
                                                            </div>
                                                                </div>
                                                                  <% end %>
                                                               

                                                                </div>
</div>

app/views/requests/new.html.erb
<div class="container">
<br>
<br>
<br>
<center><h3>New Request</h3></center>
<%= render 'form' %>

</div>

app/views/requests/show.html.erb
 <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>

<div class="container">
	<div class="row">
      <div class="col-md-4 col-md-offset-4">
      <center>
		   <div class="panel panel-default">
             <div class="panel-body">
               <center>




       <% if @request.completed? %>
      
     

      <h1> This request was completed  </h1>

       <% else %>

      <%if @request.user.provider=='facebook' %>
        <p>Requested by <%= link_to(@request.user.name, @request.user) %></p>
        <%= link_to (image_tag @request.user.image, :class=> "img-circular"), @request.user %>
        <% else %>
          <p>Requested by <%= link_to(@request.user.first_name, @request.user) %></p>
          <%= link_to (image_tag @request.user.avatar, :class=> "img-circular"), @request.user %>

          <% end %>

	
	    
	

	       <p>Member since<%= @request.user.created_at.strftime(" %b %d, %Y") %></p>
	      <p><%= link_to("View Profile", @request.user) %><p>
      </center>
	 
     </div>
       </div>
         </div>

     							

     							<div class="container">
         				<div class="row">
        



              <div class="col-md-4 col-md-offset-4">
       <div class="panel panel-default">
         
         <div class="panel-body">
         <center><h3><b><%= @request.title %></b></h3></center>

			
			<center><p><%= @request.body    %></p></center>
    
		 







<%-# link_to("Seller's Profile", @request.user) %>




<% end %>






<%#= link_to :recipient_id => @request.user.id(type: "submit", class: "btn btn-primary") do %>


 




  <p align="center"><p></p>

    










<p style="text-align:left;">
&nbsp;<span class="glyphicon glyphicon-eye-open glyphicon-align-left" aria-hidden="true"></span>&nbsp;<%=  @request.city.try(:name)    %>
<span style="float:right;"><%= @request.created_at.strftime(" %b %d, %Y") %></span>
</p>
</div>
</div>
</div>
</div>
</div>


<% if user_signed_in? %>

<% if @request.user_id == current_user.id %>

 <div class="col-md-4 col-md-offset-4">
       <div class="panel panel-default">
         
         <div class="panel-body">
    
   
<center><%= link_to complete_request_path(@request), method: :patch do %></p>
<i class="fa fa-check fa-lg"></i><% end %><%= link_to "Edit", edit_request_path(@request) ,class: "btn btn-md btn-primary"  %>
<%= link_to "Delete", request_path(@request), method: :delete, data: { confirm: "Are you sure to permanently delete this listed request?" }, class: "btn btn-md btn-danger" %></center>

         </div>
         </div>
         </div>
  <% end %>
  <% end %>


 <% if @request.completed? %>

<% else %>

 <div class="col-md-4 col-md-offset-4">
		   <div class="panel panel-default">
         
         <div class="panel-body">
         <center><h3><b>Payout</b></h3></center>
         <%if @request.user.provider=='facebook' %>

         <p> <%= @request.user.name %> is offering Ksh <%= number_with_delimiter(@request.budget, :delimiter => ',') %>/- if you complete this request</p>
         <% else %>
   <p> <%= @request.user.first_name %> is offering Ksh <%= number_with_delimiter(@request.budget, :delimiter => ',') %>/- if you complete this request</p>
         </div>
         </div>
         </div>
         <% end %>



        


 <div class="col-md-4 col-md-offset-4">
		   <div class="panel panel-default">
         
         <div class="panel-body">
         <center>
         
     
     <p>Can you fullfill this request?<p>


   <div class="ui primary circular segment">
  <h2 class="ui header">
    Contact
    <div class="sub header"><%= @request.contact %></div>
  </h2>
</div>
   <% end %>




   
    <% if user_signed_in? %>
   
	<%if @request.user_id == current_user.id %>

  <%if @request.completed? %>

	<% else %>



   <center><%= link_to "Send Message", new_conversation_path(:recipient_id => @request.user.id), class: "btn btn-large btn-primary"%></center>
    
	<%#= link_to "Message Seller", new_conversation_path(:recipient_id => @request.user.id), class: "btn btn-large btn-primary" %>
	<% end %>
	<% end %>
  <% end %>
	</center>
	</center>
    </div>
    </div>
    </div>